export const INPUT_INITIAL_VALUE = {
	value: "",
	error: false
};

export const PC_ESSENTIALS = [
	"CPU",
	"CPU Cooler",
	"Motherboard",
	"Memory",
	"Storage",
	"Video Card",
	"Case",
	"Power Supply",
	"OS",
	"Monitor"
];

export const EXPANSION_CARDS = [
	"Sound Cards",
	"Wired Network Adapters",
	"Wireless Network Adapters"
];

export const PERIPHERALS = ["Headphones", "Keyboards", "Mice", "Speakers", "Webcams"];

export const ACCESSORIES_OTHERS = [
	"Case Accessories",
	"Case Fans",
	"Fan Controllers",
	"Thermal Compound",
	"External Storage",
	"Optical Drive",
	"UPS Systems"
];

export const DEFAULT_SPECIFICATION_DETAILS = {
	CPU: {
		manufacturer: "amd",
		core: "",
		performanceCoreClock: "",
		performanceBoostClock: "",
		TDP: "",
		series: "",
		microArchitechture: "",
		coreFamily: "",
		socket: "",
		integratedGraphics: "",
		maxSupportedMemory: "",
		eccSupport: "true",
		includesCooler: "true",
		packaging: "",
		l1Cache: "",
		l2Cache: "",
		l3Cache: "",
		lithography: "",
		includesCPUCooler: "false",
		multithreading: "false",
		typeOfMultithreading: ""
	},
	CPU_COOLER: {
		manufacturer: "",
		model: "",
		fanRPM: "",
		noiseLevel: "",
		color: "",
		height: "",
		cpuSocket: "",
		waterCooled: "false",
		fanless: "false"
	},
	MOTHERBOARD: {
		manufacturer: "",
		socketCpu: "",
		formFactor: "",
		chipset: "",
		maxMemory: "",
		memoryType: "DDR4",
		memorySlots: "",
		memorySpeed: "",
		color: "",
		sliCrossfire: "",
		pci16Slots: "",
		pci8Slots: "",
		pci4Slots: "",
		pci1Slots: "",
		pciSlots: "",
		m2Slots: "",
		miniPCIeSlots: "",
		halfMiniPCIeSlots: "",
		miniPCIe_mSATASlots: "",
		mSataSlots: "",
		sata6Gb: "",
		onboardEthernet: "",
		onboardVideo: "",
		usb2Headers: "",
		singleUsb2Headers: "",
		usb3_2Gen1Headers: "",
		usb3_2Gen2Headers: "",
		usb3_2Gen2x2Headers: "",
		supportsECC: "false",
		wirelessNetworking: "",
		raidSupport: "false"
	},
	MEMORY: {
		manufacturer: "",
		speed: "",
		formFactor: "",
		modules: "",
		color: "",
		firstWordLatency: "",
		CASLatency: "",
		voltage: "",
		timing: "",
		ecc_Registered: "",
		heatSpreader: "true"
	},
	STORAGE: {
		manufacturer: "",
		capacity: "",
		type: "",
		cache: "",
		formFactor: "",
		interface: "",
		nvme: "true"
	},
	VIDEO_CARD: {
		manufacturer: "",
		model: "",
		chipset: "",
		memory: "",
		memoryType: "",
		coreClock: "",
		boostClock: "",
		effectiveMemoryClock: "",
		interface: "",
		color: "",
		frameSync: "",
		length: "",
		TDP: "",
		caseExpansionSlotWidth: "",
		totalSlotWidth: "",
		cooling: "",
		externalPower: "",
		dviOutputs: "",
		hdmiOutputs: "",
		displayPortOutputs: ""
	},
	CASING: {
		manufacturer: "",
		type: "",
		color: "",
		powerSupply: "",
		sidePanel: "",
		powerSupplyShroud: "true",
		frontPanelUSB: "",
		motherboardFormFactor: "",
		maxLength: "",
		driveBays: "",
		expansionSlots: "",
		dimensions: "",
		volume: ""
	},
	POWER_SUPPLY: {
		manufacturer: "",
		model: "",
		type: "",
		efficiencyRating: "",
		wattage: "",
		length: "",
		modular: "true",
		color: "",
		fanless: "true",
		atx4pinConnectors: "",
		eps8pinConnectors: "",
		pcie12_4pin12VHPWRconnectors: "",
		pcie12pinConnectors: "",
		pcie8pinConnectors: "",
		pcie6_2pinConnectors: "",
		pcie6pinConnectors: "",
		sataConnectors: "",
		molex4pinConnectors: ""
	},
	OPERATING_SYSTEM: {
		manufacturer: "",
		model: "",
		mode: "",
		version: "",
		maxSupportedMemory: "",
		features: ""
	},
	MONITOR: {
		manufacturer: "",
		model: "",
		screenSize: "",
		resolution: "",
		refreshRate: "",
		responseTimeG2G: "",
		panelType: "",
		aspectRatio: "",
		color: "",
		brightness: "",
		hdrTier: "",
		widescreen: "true",
		curvedScreen: "true",
		frameSync: "",
		builtInSpeakers: "true",
		viewingAngle: "",
		inputs: ""
	},
	SOUND_CARD: {
		manufacturer: "",
		model: "",
		channels: "",
		digitalAudio: "",
		signalToNoiseRatio: "",
		sampleRate: "",
		chipSet: "",
		interface: "",
		color: ""
	},
	WIRED_NETWORK_ADAPTER: {
		manufacturer: "",
		interface: "",
		features: ""
	},
	WIRELESS_NETWORK_ADAPTER: {
		manufacturer: "",
		protocol: "",
		interface: "",
		security: "",
		antenna: "",
		features: ""
	},
	HEADPHONE: {
		manufacturer: "",
		model: "",
		type: "",
		frequencyResponse: "",
		microphone: "true",
		wireless: "true",
		enclosureType: "",
		color: "",
		activeNoiseCancelling: "true",
		connection: "",
		channels: "",
		impedance: "",
		sensitivity: ""
	},
	KEYBOARD: {
		manufacturer: "",
		model: "",
		style: "",
		mechanical: "true",
		switchType: "",
		backlit: "",
		tenkeyless: "true",
		connectionType: "",
		color: "",
		mouseIncluded: "false",
		features: ""
	},
	MICE: {
		manufacturer: "",
		model: "",
		trackingMethod: "",
		connectionType: "",
		maxDPI: "",
		handOrientation: "",
		color: "",
		features: ""
	},
	SPEAKER: {
		manufacturer: "",
		model: "",
		configuration: "",
		totalWattage: "",
		frequencyResponse: "",
		color: "",
		powerEachFront: "",
		powerCenter: "",
		powerEachRear: "",
		powerSubwoofer: "",
		features: ""
	},
	WEBCAM: {
		manufacturer: "",
		model: "",
		resolution: "",
		connection: "",
		focusType: "",
		operatingSystem: "",
		fovAngle: "",
		fStop: "",
		focalLength: "",
		privacyShutter: "false",
		builtInLightning: "false",
		automaticLightningAdjust: "false"
	},
	CASE_ACCESSORIES: {
		manufacturer: "",
		model: "",
		type: "",
		formFactor: "",
		features: ""
	},
	CASE_FAN: {
		manufacturer: "",
		model: "",
		size: "",
		color: "",
		quantity: "",
		rpm: "",
		airflow: "",
		noiseLevel: "",
		pwm: "true",
		led: "",
		connector: "",
		controller: "",
		staticPressure: ""
	},
	FAN_CONTROLLER: {
		manufacturer: "",
		model: "",
		channels: "",
		channelWattage: "",
		pwm4pin: "false",
		formFactor: "",
		color: "",
		features: ""
	},
	THERMAL_COMPOUND: {
		manufacturer: "",
		model: "",
		amount: "",
		features: ""
	},
	EXTERNAL_STORAGE: {
		manufacturer: "",
		model: "",
		type: "",
		interface: "",
		capacity: "",
		color: "",
		rpm: ""
	},
	OPTICAL_DRIVE: {
		manufacturer: "",
		model: "",
		formFactor: "",
		interface: "",
		bufferCache: "",
		dvd_romSpeed: "",
		cd_romSpeed: "",
		bd_rSpeed: "",
		bd_rDualLayerSpeed: "",
		bd_reSpeed: "",
		bd_reDualLayerSpeed: "",
		dvdRWSpeed: "",
		dvdRDualLayerSpeed: "",
		dvd_rSpeed: "",
		dvd_rwSpeed: "",
		dvd_rDualLayerSpeed: "",
		dvd_ramSpeed: "",
		cd_rSpeed: "",
		cd_rwSpeed: "",
		features: ""
	},
	UPS: {
		manufacturer: "",
		capacityW: "",
		capacityVA: "",
		rackHeight: "",
		backupRunTimeFullLoad: "",
		backupRunTimeHalfLoad: "",
		batteryChemistry: "",
		dataLineProtection: "",
		emergencyPowerOff: "true",
		formFactor: "",
		hotSwappable: "false",
		inputVoltage: "",
		maxBatteryRechargeTime: "",
		outputVoltage: "",
		receptacles: "",
		serialPort: "true",
		waveformType: "",
		features: ""
	}
};
